// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZw4-JZyKADiBiHPAdy2zGG6iRh7d1UoY',
    appId: '1:179319785860:web:6098fe15c9a085856bb5d1',
    messagingSenderId: '179319785860',
    projectId: 'mynote-flutt1',
    authDomain: 'mynote-flutt1.firebaseapp.com',
    storageBucket: 'mynote-flutt1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdfnKDFadFitvgirJ-teR8UQwN3P3TJgI',
    appId: '1:179319785860:android:204d9294f36405d96bb5d1',
    messagingSenderId: '179319785860',
    projectId: 'mynote-flutt1',
    storageBucket: 'mynote-flutt1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB66cISLPeucP9KP_fiz4e182T7g_Utx2g',
    appId: '1:179319785860:ios:245ba58f3b796a476bb5d1',
    messagingSenderId: '179319785860',
    projectId: 'mynote-flutt1',
    storageBucket: 'mynote-flutt1.appspot.com',
    iosClientId: '179319785860-fstn8su22pdqt865qcirqgjbjta2vo78.apps.googleusercontent.com',
    iosBundleId: 'com.making.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB66cISLPeucP9KP_fiz4e182T7g_Utx2g',
    appId: '1:179319785860:ios:245ba58f3b796a476bb5d1',
    messagingSenderId: '179319785860',
    projectId: 'mynote-flutt1',
    storageBucket: 'mynote-flutt1.appspot.com',
    iosClientId: '179319785860-fstn8su22pdqt865qcirqgjbjta2vo78.apps.googleusercontent.com',
    iosBundleId: 'com.making.mynotes',
  );
}
